# Generated by Django 3.0.4 on 2020-06-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNARecord',
            fields=[
                ('coords', models.CharField(max_length=40)),
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DNASeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('combined', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Superfamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField()),
                ('length', models.IntegerField()),
                ('dnarecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteinseq', to='query.DNARecord')),
                ('proteinname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.ProteinName')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('superfamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Superfamily')),
            ],
        ),
        migrations.AddField(
            model_name='dnarecord',
            name='dnaseq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.DNASeq'),
        ),
        migrations.AddField(
            model_name='dnarecord',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Family'),
        ),
        migrations.AddField(
            model_name='dnarecord',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Genome'),
        ),
    ]
