# Generated by Django 3.0.4 on 2020-09-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNARecord',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('coords', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DNASeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Superfamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinSeq',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('seq', models.TextField()),
                ('length', models.IntegerField()),
                ('dnarecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteinseq', to='query.DNARecord')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_checked_uniprot', models.DateField(blank=True, null=True)),
                ('uniprot_new_seq', models.TextField(blank=True, null=True)),
                ('function_updated', models.DateField(blank=True, null=True)),
                ('sequence_updated', models.DateField(blank=True, null=True)),
                ('uniprot_accession', models.CharField(max_length=10)),
                ('uniprot_link', models.URLField(blank=True, null=True)),
                ('base_sequence', models.TextField(blank=True, null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('proteinseq', models.ManyToManyField(blank=True, null=True, to='query.ProteinSeq')),
                ('superfamily', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.Superfamily')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('superfamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Superfamily')),
            ],
        ),
        migrations.AddField(
            model_name='dnarecord',
            name='dnaseq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.DNASeq'),
        ),
        migrations.AddField(
            model_name='dnarecord',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Family'),
        ),
        migrations.AddField(
            model_name='dnarecord',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Genome'),
        ),
    ]
