# Generated by Django 3.0.4 on 2020-06-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20200602_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnarecord',
            name='dnaseq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.DNASeq'),
        ),
    ]
