# Generated by Django 3.0.4 on 2020-06-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20200602_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinname',
            name='superfamily',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.PROTECT, to='query.Superfamily'),
            preserve_default=False,
        ),
    ]
