# Generated by Django 3.0.4 on 2020-06-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20200611_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinname',
            name='uniprot_accession',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
