# Generated by Django 3.0.4 on 2020-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_proteinname_superfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinname',
            name='function_updated',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='proteinname',
            name='last_checked_uniprot',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='proteinname',
            name='sequence_updated',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='proteinname',
            name='uniprot_new_seq',
            field=models.TextField(default=None),
        ),
    ]
