# Generated by Django 3.0.4 on 2020-06-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20200611_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinname',
            name='function_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteinname',
            name='last_checked_uniprot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteinname',
            name='sequence_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteinname',
            name='uniprot_new_seq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
