# Generated by Django 3.0.4 on 2020-06-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_proteinname_uniprot_accession'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinname',
            name='base_sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteinname',
            name='uniprot_accession',
            field=models.CharField(max_length=10),
        ),
    ]
