# Generated by Django 3.0.4 on 2020-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20200611_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinname',
            name='function',
            field=models.TextField(blank=True, null=True),
        ),
    ]
