# Generated by Django 3.0.4 on 2020-06-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_proteinname_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinname',
            name='uniprot_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
