# Generated by Django 3.0.4 on 2020-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_proteinname_uniprot_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TissueExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue', models.CharField(max_length=30)),
            ],
        ),
    ]
