# Generated by Django 3.0.4 on 2020-06-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0011_tissueexpression'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TissueExpression',
        ),
    ]
